Essential 배포 시스템 추가
tmax-cloud/hypercloud5-integrated-distribution pull request #5
Opened 2022-08-08 06:26 UTC by sisilia91

2022-08-08 06:38 UTC, aldlfkahs requested changes
코멘트 참고하여 수정해주세요

2022-08-08 06:38 UTC, aldlfkahs commented on Jenkinsfile
> +					sh "cp ${homeDir}/convert/result/output.xls translation/translation-v${version}.xls"
여기도 바로 위에 essential처럼 xxx-crd-translation-v${version}.xls 형식으로 바꿔주세요

2022-08-08 09:47 UTC, sisilia91 commented on Jenkinsfile
> +					sh "cp ${homeDir}/convert/result/output.xls translation/translation-v${version}.xls"
수정하였습니다. 확인바랍니다.

2022-08-08 09:56 UTC, sjoh0704 approved these changes

2022-08-09 00:46 UTC, aldlfkahs approved these changes

2022-08-09 03:37 UTC, merged